set(EI_ESP_NN_ROOT "${EI_SDK_DIR}/porting/espressif/ESP-NN")
set(EI_ESP_NN_COMPILE_DEFINITIONS
    EI_CLASSIFIER_TFLITE_ENABLE_ESP_NN=1
    EI_CLASSIFIER_TFLITE_ENABLE_ESP_NN_S3=1
)

RECURSIVE_FIND_FILE(EI_ESP_NN_C_SOURCES "${EI_ESP_NN_ROOT}" "*.c")
RECURSIVE_FIND_FILE(EI_ESP_NN_ASM_SOURCES "${EI_ESP_NN_ROOT}" "*.S")
