#include "dashboard_page.h"

static const char DASHBOARD_HTML[] =
    "<!doctype html><html lang=\"en\"><head>"
    "<meta charset=\"utf-8\">"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
    "<title>EdgeDeploy inference dashboard</title>"
    "<style>"
    "*{box-sizing:border-box}"
    "body{font-family:system-ui,sans-serif;max-width:760px;margin:2rem auto;"
    "padding:0 1rem;background:#f5f7fa;color:#172033}"
    ".card{background:#fff;border-radius:16px;padding:1.25rem;"
    "box-shadow:0 8px 28px #18243a1f}"
    ".visual-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));"
    "gap:1rem;margin:1rem 0}"
    ".visual-panel{border:1px solid #dce3ed;border-radius:12px;padding:1rem;"
    "text-align:center;background:#fbfcfe}"
    ".visual-panel h2{font-size:1rem;margin:0 0 .5rem}"
    "img{display:block;width:128px;height:128px;max-width:100%;margin:.5rem auto;"
    "image-rendering:auto;background:#e7ebf0;border-radius:10px;object-fit:contain}"
    ".muted{min-height:1.4rem;color:#59677d;font-size:.9rem}"
    ".controls{display:flex;gap:.75rem;flex-wrap:wrap;margin-top:.75rem}"
    "button{border:0;border-radius:9px;padding:.7rem 1rem;font-weight:650;"
    "cursor:pointer;background:#155eef;color:white}"
    "button.secondary{background:#e7ecf5;color:#172033}"
    ".result{border-top:1px solid #dce3ed;margin-top:1rem;padding-top:1rem}"
    ".prediction{font-size:1.25rem;font-weight:750;margin:.25rem 0}"
    ".scores{display:grid;gap:.45rem;margin:.75rem 0}"
    ".score-row{display:flex;justify-content:space-between;gap:1rem;"
    "padding:.45rem .65rem;background:#f2f5f9;border-radius:8px}"
    "#timing{color:#46546a}"
    "@media(max-width:560px){.visual-grid{grid-template-columns:1fr}}"
    "</style></head><body><main class=\"card\">"
    "<h1>EdgeDeploy dashboard</h1>"
    "<p>Live OV5640 preview and the exact frame used by the classifier.</p>"
    "<section class=\"visual-grid\">"
    "<article class=\"visual-panel\"><h2>Live preview</h2>"
    "<img id=\"livePreview\" alt=\"Live camera preview\">"
    "<p id=\"liveStatus\" class=\"muted\">Starting preview...</p></article>"
    "<article class=\"visual-panel\"><h2>Inference snapshot</h2>"
    "<img id=\"inferenceSnapshot\" alt=\"Latest inference frame\">"
    "<p id=\"inferenceStatus\" class=\"muted\">Waiting for first inference</p>"
    "</article></section>"
    "<div class=\"controls\">"
    "<button id=\"captureButton\" type=\"button\">Capture now</button>"
    "<button id=\"streamButton\" class=\"secondary\" type=\"button\">"
    "Pause preview</button></div>"
    "<section class=\"result\" aria-live=\"polite\">"
    "<h2>Latest result</h2>"
    "<p id=\"prediction\" class=\"prediction\">No result yet</p>"
    "<div id=\"scores\" class=\"scores\"></div>"
    "<p id=\"timing\">Timing will appear after the first inference.</p>"
    "</section>"
    "<script>"
    "const livePreview=document.getElementById('livePreview');"
    "const inferenceSnapshot=document.getElementById('inferenceSnapshot');"
    "const liveStatus=document.getElementById('liveStatus');"
    "const inferenceStatus=document.getElementById('inferenceStatus');"
    "const prediction=document.getElementById('prediction');"
    "const scores=document.getElementById('scores');"
    "const timing=document.getElementById('timing');"
    "const captureButton=document.getElementById('captureButton');"
    "const streamButton=document.getElementById('streamButton');"
    "const streamUrl=`http://${location.hostname}:81/stream`;"
    "let streaming=false;let displayedSequence=0;let pendingSequence=0;"
    "let inferenceObjectUrl=null;let pollRunning=false;"
    "function startStream(){"
    "livePreview.src=`${streamUrl}?t=${Date.now()}`;streaming=true;"
    "streamButton.textContent='Pause preview';"
    "liveStatus.textContent='Streaming at up to 15 FPS';}"
    "function stopStream(){livePreview.removeAttribute('src');streaming=false;"
    "streamButton.textContent='Resume preview';liveStatus.textContent='Preview paused';}"
    "function renderResult(metadata){"
    "prediction.textContent=`${metadata.prediction} (${metadata.confidence.toFixed(5)})`;"
    "scores.replaceChildren();"
    "metadata.scores.forEach(item=>{const row=document.createElement('div');"
    "row.className='score-row';const label=document.createElement('span');"
    "const value=document.createElement('strong');label.textContent=item.label;"
    "value.textContent=item.value.toFixed(5);row.append(label,value);scores.append(row);});"
    "timing.textContent=`DSP ${metadata.timing.dsp_ms} ms · classification "
    "${metadata.timing.classification_ms} ms · anomaly ${metadata.timing.anomaly_ms} ms`;"
    "}"
    "async function pollInference(){if(pollRunning)return;pollRunning=true;"
    "try{const metadataResponse=await fetch('/api/inference',{cache:'no-store'});"
    "if(!metadataResponse.ok)throw new Error(`metadata HTTP ${metadataResponse.status}`);"
    "const metadata=await metadataResponse.json();"
    "if(!metadata.ready){inferenceStatus.textContent='Waiting for first inference';return;}"
    "if(metadata.sequence===displayedSequence){"
    "inferenceStatus.textContent=`Sequence ${metadata.sequence} · ${metadata.age_ms} ms ago`;return;}"
    "if(metadata.sequence===pendingSequence)return;pendingSequence=metadata.sequence;"
    "const response=await fetch(`/api/inference/image?sequence=${metadata.sequence}`,"
    "{cache:'no-store'});"
    "if(response.status===409){pendingSequence=0;return;}"
    "if(!response.ok)throw new Error(`image HTTP ${response.status}`);"
    "const responseSequence=Number(response.headers.get('X-Inference-Sequence'));"
    "if(responseSequence!==metadata.sequence){pendingSequence=0;return;}"
    "const blob=await response.blob();const nextUrl=URL.createObjectURL(blob);"
    "await new Promise((resolve,reject)=>{"
    "inferenceSnapshot.onload=()=>{if(pendingSequence!==metadata.sequence){"
    "URL.revokeObjectURL(nextUrl);reject(new Error('superseded image'));return;}"
    "const previousUrl=inferenceObjectUrl;inferenceObjectUrl=nextUrl;"
    "displayedSequence=metadata.sequence;pendingSequence=0;renderResult(metadata);"
    "inferenceStatus.textContent=`Sequence ${metadata.sequence} · ${metadata.age_ms} ms ago`;"
    "if(previousUrl)URL.revokeObjectURL(previousUrl);inferenceSnapshot.onload=null;"
    "inferenceSnapshot.onerror=null;resolve();};"
    "inferenceSnapshot.onerror=()=>{URL.revokeObjectURL(nextUrl);pendingSequence=0;"
    "inferenceSnapshot.onload=null;inferenceSnapshot.onerror=null;"
    "reject(new Error('image decode failed'));};inferenceSnapshot.src=nextUrl;});"
    "}catch(error){pendingSequence=0;inferenceStatus.textContent=`Update failed: ${error.message}`;}"
    "finally{pollRunning=false;}}"
    "captureButton.addEventListener('click',()=>{"
    "window.open(`/capture?t=${Date.now()}`,'_blank','noopener');});"
    "streamButton.addEventListener('click',()=>{if(streaming)stopStream();else startStream();});"
    "livePreview.addEventListener('error',()=>{if(streaming)"
    "liveStatus.textContent='Stream disconnected; pause and resume to retry';});"
    "startStream();pollInference();setInterval(pollInference,1000);"
    "</script></main></body></html>";

const char *http_capture_dashboard_html(void)
{
    return DASHBOARD_HTML;
}
