#include "dashboard_page.h"

static const char DASHBOARD_HTML[] =
    "<!doctype html><html lang=\"en\"><head>"
    "<meta charset=\"utf-8\">"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
    "<title>EdgeDeploy inference dashboard</title>"
    "<style>"
    "*{box-sizing:border-box}"
    "body{font-family:system-ui,sans-serif;max-width:760px;margin:2rem auto;"
    "padding:0 1rem;background:#f5f7fa;color:#172033}"
    ".card{background:#fff;border-radius:16px;padding:1.25rem;"
    "box-shadow:0 8px 28px #18243a1f}"
    ".visual-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));"
    "gap:1rem;margin:1rem 0}"
    ".visual-panel{border:1px solid #dce3ed;border-radius:12px;padding:1rem;"
    "text-align:center;background:#fbfcfe}"
    ".visual-panel h2{font-size:1rem;margin:0 0 .5rem}"
    "img{display:block;width:128px;height:128px;max-width:100%;margin:.5rem auto;"
    "image-rendering:auto;background:#e7ebf0;border-radius:10px;object-fit:contain}"
    ".muted{min-height:1.4rem;color:#59677d;font-size:.9rem}"
    ".result{border-top:1px solid #dce3ed;margin-top:1rem;padding-top:1rem}"
    ".prediction{font-size:1.25rem;font-weight:800;"
    "text-align:center;color:#155eef;margin:.25rem 0}"
    ".scores{display:grid;gap:.45rem;margin:.75rem 0}"
    ".score-row{display:flex;justify-content:space-between;gap:1rem;"
    "padding:.45rem .65rem;background:#f2f5f9;border-radius:8px}"
    "#timing{color:#46546a}"
    ".health-panel{border-top:1px solid #dce3ed;margin-top:1rem;padding-top:1rem}"
    ".health-head{display:flex;align-items:center;gap:.75rem}"
    ".health-title{flex:1}.health-title h2{font-size:1.05rem;margin:0}"
    ".health-title p{color:#59677d;font-size:.82rem;margin:.2rem 0 0}"
    ".health-state{font-size:.82rem;font-weight:750;color:#067647}"
    ".health-state.degraded{color:#b54708}.health-state.starting{color:#46546a}"
    ".health-toggle{width:44px;height:24px;border:0;border-radius:14px;"
    "background:#98a2b3;position:relative;cursor:pointer;padding:0}"
    ".health-toggle:after{content:'';position:absolute;width:18px;height:18px;"
    "left:3px;top:3px;border-radius:50%;background:#fff;transition:.18s}"
    ".health-toggle[aria-checked='true']{background:#155eef}"
    ".health-toggle[aria-checked='true']:after{left:23px}"
    ".health-toggle:disabled{cursor:wait;opacity:.65}"
    ".health-off{font-size:.86rem;color:#59677d;background:#f9fafb;"
    "border-radius:9px;padding:.7rem .8rem;margin:.75rem 0 0}"
    ".health-metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));"
    "gap:.55rem;margin-top:.85rem}"
    ".health-metric{border:1px solid #e4e7ec;background:#fbfcfe;"
    "border-radius:9px;padding:.65rem}"
    ".health-metric span{display:block;color:#667085;font-size:.72rem}"
    ".health-metric strong{display:block;font-size:.95rem;margin-top:.18rem}"
    ".health-charts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));"
    "gap:.65rem;margin-top:.65rem}"
    ".health-chart{border:1px solid #e4e7ec;border-radius:10px;padding:.65rem;"
    "background:#fff}.health-chart h3{font-size:.82rem;margin:0}"
    ".health-chart p{font-size:.7rem;color:#667085;margin:.12rem 0 .3rem}"
    ".health-chart svg{display:block;width:100%;height:118px;overflow:visible}"
    ".chart-head{display:flex;align-items:baseline;justify-content:space-between;gap:.5rem}"
    ".chart-head strong{font-size:.7rem;color:#475467}"
    ".chart-grid{stroke:#eaecf0;stroke-width:1}"
    ".chart-tick,.chart-time{fill:#667085;font-size:8px}"
    ".chart-tick{text-anchor:end}.chart-time-now{text-anchor:end}"
    ".chart-latency{fill:none;"
    "stroke:#155eef;stroke-width:2.2}.chart-free{fill:none;stroke:#12b76a;"
    "stroke-width:2.2}.chart-largest{fill:none;stroke:#7f56d9;stroke-width:2.2}"
    ".chart-legend{display:flex;flex-wrap:wrap;gap:.35rem .75rem;"
    "color:#667085;font-size:.68rem}.chart-legend strong{color:#344054}"
    ".legend-key{display:inline-block;width:.7rem;height:2px;vertical-align:.2rem;"
    "margin-right:.25rem}.legend-free{background:#12b76a}"
    ".legend-largest{background:#7f56d9}"
    ".health-reasons{background:#fff4ed;color:#b54708;border-radius:8px;"
    "padding:.55rem .7rem;font-size:.78rem;margin:.65rem 0 0}"
    "[hidden]{display:none!important}"
    "@media(max-width:560px){.visual-grid,.health-charts{grid-template-columns:1fr}"
    ".health-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}}"
    "</style></head><body><main class=\"card\">"
    "<h1>EdgeDeploy dashboard</h1>"
    "<p>Live OV5640 preview and the exact frame used by the classifier.</p>"
    "<section class=\"visual-grid\">"
    "<article class=\"visual-panel\"><h2>Live preview</h2>"
    "<img id=\"livePreview\" alt=\"Live camera preview\"></article>"
    "<article class=\"visual-panel\"><h2>Inference snapshot</h2>"
    "<img id=\"inferenceSnapshot\" alt=\"Latest inference frame\">"
    "<p id=\"inferenceStatus\" class=\"muted\">Waiting for first inference</p>"
    "</article></section>"
    "<section class=\"result\" aria-live=\"polite\">"
    "<h2>Latest result</h2>"
    "<p id=\"prediction\" class=\"prediction\">No result yet</p>"
    "<div id=\"scores\" class=\"scores\"></div>"
    "<p id=\"timing\">Timing will appear after the first inference.</p>"
    "</section>"
    "<section id=\"healthPanel\" class=\"health-panel\">"
    "<div class=\"health-head\"><div class=\"health-title\">"
    "<h2>Runtime health</h2><p id=\"healthSubtitle\">未开启</p></div>"
    "<span id=\"healthState\" class=\"health-state\" hidden></span>"
    "<button id=\"healthToggle\" class=\"health-toggle\" type=\"button\" "
    "role=\"switch\" aria-checked=\"false\" "
    "aria-label=\"Toggle runtime health\"></button></div>"
    "<p id=\"healthOffCopy\" class=\"health-off\">"
    "健康任务未开启，网页不请求健康数据，不占用监控任务栈。</p>"
    "<div id=\"healthPanelBody\" hidden>"
    "<div class=\"health-metrics\">"
    "<div class=\"health-metric\"><span>推理成功 / 尝试</span>"
    "<strong id=\"healthInferenceCount\">—</strong></div>"
    "<div class=\"health-metric\"><span>当前 / 峰值耗时</span>"
    "<strong id=\"healthDuration\">—</strong></div>"
    "<div class=\"health-metric\"><span>连续失败</span>"
    "<strong id=\"healthFailures\">—</strong></div>"
    "<div class=\"health-metric\"><span>推理任务栈余量</span>"
    "<strong id=\"healthInferenceStack\">—</strong></div>"
    "<div class=\"health-metric\"><span>健康任务栈余量</span>"
    "<strong id=\"healthTaskStack\">—</strong></div>"
    "<div class=\"health-metric\"><span>PSRAM 空闲 / 最低</span>"
    "<strong id=\"healthPsram\">—</strong></div></div>"
    "<div class=\"health-charts\">"
    "<article class=\"health-chart\"><div class=\"chart-head\">"
    "<h3>推理耗时趋势</h3><strong id=\"latencyCurrent\">—</strong></div>"
    "<p>最近 60 秒 · ms</p><svg viewBox=\"0 0 300 118\" "
    "aria-label=\"Inference duration chart\">"
    "<line class=\"chart-grid\" x1=\"44\" y1=\"10\" x2=\"292\" y2=\"10\"></line>"
    "<line class=\"chart-grid\" x1=\"44\" y1=\"49\" x2=\"292\" y2=\"49\"></line>"
    "<line class=\"chart-grid\" x1=\"44\" y1=\"88\" x2=\"292\" y2=\"88\"></line>"
    "<text id=\"latencyTickTop\" class=\"chart-tick\" x=\"38\" y=\"13\">—</text>"
    "<text id=\"latencyTickMiddle\" class=\"chart-tick\" x=\"38\" y=\"52\">—</text>"
    "<text id=\"latencyTickBottom\" class=\"chart-tick\" x=\"38\" y=\"91\">—</text>"
    "<text id=\"latencyAge\" class=\"chart-time\" x=\"44\" y=\"108\">—</text>"
    "<text class=\"chart-time chart-time-now\" x=\"292\" y=\"108\">现在</text>"
    "<path id=\"latencyPath\" class=\"chart-latency\"></path></svg></article>"
    "<article class=\"health-chart\"><div class=\"chart-head\">"
    "<h3>内部内存趋势</h3></div>"
    "<p>最近 60 秒 · KiB</p><svg viewBox=\"0 0 300 118\" "
    "aria-label=\"Internal memory chart\">"
    "<line class=\"chart-grid\" x1=\"44\" y1=\"10\" x2=\"292\" y2=\"10\"></line>"
    "<line class=\"chart-grid\" x1=\"44\" y1=\"49\" x2=\"292\" y2=\"49\"></line>"
    "<line class=\"chart-grid\" x1=\"44\" y1=\"88\" x2=\"292\" y2=\"88\"></line>"
    "<text id=\"memoryTickTop\" class=\"chart-tick\" x=\"38\" y=\"13\">—</text>"
    "<text id=\"memoryTickMiddle\" class=\"chart-tick\" x=\"38\" y=\"52\">—</text>"
    "<text id=\"memoryTickBottom\" class=\"chart-tick\" x=\"38\" y=\"91\">—</text>"
    "<text id=\"memoryAge\" class=\"chart-time\" x=\"44\" y=\"108\">—</text>"
    "<text class=\"chart-time chart-time-now\" x=\"292\" y=\"108\">现在</text>"
    "<path id=\"memoryFreePath\" class=\"chart-free\"></path>"
    "<path id=\"memoryLargestPath\" class=\"chart-largest\"></path></svg>"
    "<div class=\"chart-legend\"><span><i class=\"legend-key legend-free\"></i>"
    "空闲内存 <strong id=\"memoryFreeValue\">—</strong></span>"
    "<span><i class=\"legend-key legend-largest\"></i>最大连续块 "
    "<strong id=\"memoryLargestValue\">—</strong></span></div></article></div>"
    "<p id=\"healthReasons\" class=\"health-reasons\" hidden></p>"
    "</div></section>"
    "<script>"
    "const livePreview=document.getElementById('livePreview');"
    "const inferenceSnapshot=document.getElementById('inferenceSnapshot');"
    "const inferenceStatus=document.getElementById('inferenceStatus');"
    "const prediction=document.getElementById('prediction');"
    "const scores=document.getElementById('scores');"
    "const timing=document.getElementById('timing');"
    "const healthSubtitle=document.getElementById('healthSubtitle');"
    "const healthState=document.getElementById('healthState');"
    "const healthToggle=document.getElementById('healthToggle');"
    "const healthOffCopy=document.getElementById('healthOffCopy');"
    "const healthPanelBody=document.getElementById('healthPanelBody');"
    "const healthInferenceCount=document.getElementById('healthInferenceCount');"
    "const healthDuration=document.getElementById('healthDuration');"
    "const healthFailures=document.getElementById('healthFailures');"
    "const healthInferenceStack=document.getElementById('healthInferenceStack');"
    "const healthTaskStack=document.getElementById('healthTaskStack');"
    "const healthPsram=document.getElementById('healthPsram');"
    "const healthReasons=document.getElementById('healthReasons');"
    "const latencyCurrent=document.getElementById('latencyCurrent');"
    "const latencyTickTop=document.getElementById('latencyTickTop');"
    "const latencyTickMiddle=document.getElementById('latencyTickMiddle');"
    "const latencyTickBottom=document.getElementById('latencyTickBottom');"
    "const latencyAge=document.getElementById('latencyAge');"
    "const latencyPath=document.getElementById('latencyPath');"
    "const memoryTickTop=document.getElementById('memoryTickTop');"
    "const memoryTickMiddle=document.getElementById('memoryTickMiddle');"
    "const memoryTickBottom=document.getElementById('memoryTickBottom');"
    "const memoryAge=document.getElementById('memoryAge');"
    "const memoryFreePath=document.getElementById('memoryFreePath');"
    "const memoryLargestPath=document.getElementById('memoryLargestPath');"
    "const memoryFreeValue=document.getElementById('memoryFreeValue');"
    "const memoryLargestValue=document.getElementById('memoryLargestValue');"
    "const streamUrl=`http://${location.hostname}:81/stream`;"
    "let liveReconnectTimer=null;let renderedSequence=0;"
    "let displayedImageSequence=0;let pendingImageSequence=0;"
    "let inferenceObjectUrl=null;let pollRunning=false;"
    "function startStream(){"
    "liveReconnectTimer=null;"
    "livePreview.src=`${streamUrl}?t=${Date.now()}`;}"
    "function renderResult(metadata){"
    "prediction.textContent=`${metadata.prediction} (${metadata.confidence.toFixed(5)})`;"
    "scores.replaceChildren();"
    "metadata.scores.forEach(item=>{const row=document.createElement('div');"
    "row.className='score-row';const label=document.createElement('span');"
    "const value=document.createElement('strong');label.textContent=item.label;"
    "value.textContent=item.value.toFixed(5);row.append(label,value);scores.append(row);});"
    "timing.textContent=`DSP ${metadata.timing.dsp_ms} ms · classification "
    "${metadata.timing.classification_ms} ms · anomaly ${metadata.timing.anomaly_ms} ms`;"
    "}"
    "async function pollInference(){if(pollRunning)return;pollRunning=true;"
    "let imageRequestStarted=false;"
    "try{const metadataResponse=await fetch('/api/inference',{cache:'no-store'});"
    "if(!metadataResponse.ok)throw new Error(`metadata HTTP ${metadataResponse.status}`);"
    "const metadata=await metadataResponse.json();"
    "if(!metadata.ready){inferenceStatus.textContent='Waiting for first inference';return;}"
    "if(metadata.sequence!==renderedSequence){renderResult(metadata);"
    "renderedSequence=metadata.sequence;}"
    "if(metadata.sequence===displayedImageSequence){"
    "inferenceStatus.textContent=`Sequence ${metadata.sequence} · ${metadata.age_ms} ms ago`;return;}"
    "if(metadata.sequence===pendingImageSequence)return;"
    "pendingImageSequence=metadata.sequence;imageRequestStarted=true;"
    "const response=await fetch(`/api/inference/image?sequence=${metadata.sequence}`,"
    "{cache:'no-store'});"
    "if(response.status===409){pendingImageSequence=0;return;}"
    "if(!response.ok)throw new Error(`image HTTP ${response.status}`);"
    "const responseSequence=Number(response.headers.get('X-Inference-Sequence'));"
    "if(responseSequence!==metadata.sequence){pendingImageSequence=0;return;}"
    "const blob=await response.blob();const nextUrl=URL.createObjectURL(blob);"
    "const candidateImage=new Image();"
    "await new Promise((resolve,reject)=>{"
    "candidateImage.onload=()=>{candidateImage.onload=null;candidateImage.onerror=null;resolve();};"
    "candidateImage.onerror=()=>{URL.revokeObjectURL(nextUrl);pendingImageSequence=0;"
    "candidateImage.onload=null;candidateImage.onerror=null;"
    "reject(new Error('image decode failed'));};candidateImage.src=nextUrl;});"
    "if(pendingImageSequence!==metadata.sequence){URL.revokeObjectURL(nextUrl);"
    "pendingImageSequence=0;throw new Error('superseded image');}"
    "const previousUrl=inferenceObjectUrl;inferenceObjectUrl=nextUrl;"
    "inferenceSnapshot.src=nextUrl;displayedImageSequence=metadata.sequence;"
    "pendingImageSequence=0;"
    "inferenceStatus.textContent=`Sequence ${metadata.sequence} · ${metadata.age_ms} ms ago`;"
    "if(previousUrl)URL.revokeObjectURL(previousUrl);"
    "}catch(error){pendingImageSequence=0;"
    "inferenceStatus.textContent=imageRequestStarted"
    "?`Snapshot retry: ${error.message}`:`Update failed: ${error.message}`;}"
    "finally{pollRunning=false;}}"
    "const healthHistory=[];let lastHealthSequence=0;"
    "let healthPollTimer=null;let healthRequestRunning=false;"
    "let healthTransitioning=false;"
    "function setHealthPanelState(enabled,ready,state){"
    "healthToggle.setAttribute('aria-checked',enabled?'true':'false');"
    "healthOffCopy.hidden=enabled;healthPanelBody.hidden=!enabled;"
    "healthState.hidden=!enabled;"
    "if(!enabled){healthSubtitle.textContent='未开启';healthState.textContent='';return;}"
    "healthState.textContent=state==='degraded'?'Degraded':"
    "state==='healthy'?'Healthy':'Starting';"
    "healthState.className=`health-state ${state||'starting'}`;"
    "healthSubtitle.textContent=ready"
    "?'Sampling every second · 60-second browser history'"
    ":'Starting · waiting for first sample';}"
    "function startHealthPolling(){if(healthPollTimer===null){"
    "healthPollTimer=setInterval(pollHealth,1000);}}"
    "function stopHealthPolling(){if(healthPollTimer!==null){"
    "clearInterval(healthPollTimer);healthPollTimer=null;}}"
    "function clearHealthHistory(){healthHistory.length=0;lastHealthSequence=0;"
    "latencyPath.setAttribute('d','');memoryFreePath.setAttribute('d','');"
    "memoryLargestPath.setAttribute('d','');"
    "[latencyCurrent,latencyTickTop,latencyTickMiddle,latencyTickBottom,"
    "latencyAge,memoryFreeValue,memoryLargestValue,memoryTickTop,"
    "memoryTickMiddle,memoryTickBottom,memoryAge].forEach(element=>{"
    "element.textContent='—';});}"
    "const CHART_LEFT=44,CHART_RIGHT=292,CHART_TOP=10,CHART_BOTTOM=88;"
    "function niceStep(rawStep){const power=10**Math.floor(Math.log10(rawStep));"
    "const normalized=rawStep/power;"
    "const factor=normalized<=1?1:normalized<=2?2:normalized<=5?5:10;"
    "return factor*power;}"
    "function niceChartScale(values){const finite=values.filter(Number.isFinite);"
    "if(finite.length===0)return null;let low=Math.min(...finite);"
    "let high=Math.max(...finite);let span=high-low;"
    "if(span===0)span=Math.max(Math.abs(high)*.1,1);const padding=span*.1;"
    "const step=niceStep((span+2*padding)/4);"
    "const minimum=Math.max(0,Math.floor((low-padding)/step)*step);"
    "let maximum=Math.ceil((high+padding)/step)*step;"
    "if(maximum<=minimum)maximum=minimum+step;"
    "return{minimum,midpoint:(minimum+maximum)/2,maximum};}"
    "function chartPath(values,scale){if(!scale)return '';"
    "const points=values.map((value,index)=>({value:Number(value),index}))"
    ".filter(point=>Number.isFinite(point.value));if(points.length===0)return '';"
    "return points.map((point,pathIndex)=>{"
    "const x=values.length===1?(CHART_LEFT+CHART_RIGHT)/2:"
    "CHART_LEFT+point.index*(CHART_RIGHT-CHART_LEFT)/(values.length-1);"
    "const y=CHART_BOTTOM-(point.value-scale.minimum)*(CHART_BOTTOM-CHART_TOP)/"
    "(scale.maximum-scale.minimum);"
    "return `${pathIndex===0?'M':'L'}${x.toFixed(1)},${y.toFixed(1)}`;"
    "}).join(' ');}"
    "function setScaleLabels(top,middle,bottom,scale,formatter){if(!scale){"
    "top.textContent=middle.textContent=bottom.textContent='—';return;}"
    "top.textContent=formatter(scale.maximum);"
    "middle.textContent=formatter(scale.midpoint);"
    "bottom.textContent=formatter(scale.minimum);}"
    "function chartAgeLabel(){if(healthHistory.length<2)return '0 秒前';"
    "const first=Number(healthHistory[0].monitor_uptime_ms);"
    "const last=Number(healthHistory[healthHistory.length-1].monitor_uptime_ms);"
    "if(!Number.isFinite(first)||!Number.isFinite(last)||last<first)return '—';"
    "return `${Math.round((last-first)/1000)} 秒前`;}"
    "function renderHealthCharts(){if(healthHistory.length===0){"
    "clearHealthHistory();return;}"
    "const durations=healthHistory.map(item=>Number(item.inference.last_duration_ms));"
    "const durationScale=niceChartScale(durations);"
    "latencyPath.setAttribute('d',chartPath(durations,durationScale));"
    "setScaleLabels(latencyTickTop,latencyTickMiddle,latencyTickBottom,"
    "durationScale,value=>String(Math.round(value)));"
    "const latestDuration=durations[durations.length-1];"
    "latencyCurrent.textContent=Number.isFinite(latestDuration)"
    "?`当前 ${Math.round(latestDuration)} ms`:'—';"
    "latencyAge.textContent=chartAgeLabel();"
    "const free=healthHistory.map(item=>Number(item.memory.internal.free_bytes)/1024);"
    "const largest=healthHistory.map(item=>"
    "Number(item.memory.internal.largest_free_block_bytes)/1024);"
    "const memoryScale=niceChartScale(free.concat(largest));"
    "memoryFreePath.setAttribute('d',chartPath(free,memoryScale));"
    "memoryLargestPath.setAttribute('d',chartPath(largest,memoryScale));"
    "setScaleLabels(memoryTickTop,memoryTickMiddle,memoryTickBottom,"
    "memoryScale,value=>Number(value.toFixed(1)).toString());"
    "const latestFree=free[free.length-1];const latestLargest=largest[largest.length-1];"
    "memoryFreeValue.textContent=Number.isFinite(latestFree)"
    "?`${latestFree.toFixed(1)} KiB`:'—';"
    "memoryLargestValue.textContent=Number.isFinite(latestLargest)"
    "?`${latestLargest.toFixed(1)} KiB`:'—';"
    "memoryAge.textContent=chartAgeLabel();}"
    "function formatBytes(bytes){const value=Number(bytes);"
    "return value>=1048576?`${(value/1048576).toFixed(2)} MB`:"
    "`${(value/1024).toFixed(1)} KiB`; }"
    "function decodeHealthReasons(flags){const reasons=[];"
    "if(flags&1)reasons.push('推理启动超时');"
    "if(flags&2)reasons.push('推理结果过期');"
    "if(flags&4)reasons.push('连续推理失败');"
    "if(flags&8)reasons.push('推理统计不可用');"
    "const unknown=flags&~15;if(unknown)reasons.push(`未知原因 0x${unknown.toString(16)}`);"
    "return reasons;}"
    "function renderHealthSnapshot(snapshot){const inference=snapshot.inference;"
    "healthInferenceCount.textContent=`${inference.success_count} / ${inference.attempt_count}`;"
    "healthDuration.textContent=`${inference.last_duration_ms} / "
    "${inference.max_duration_ms} ms`;"
    "healthFailures.textContent=String(inference.consecutive_failure_count);"
    "healthInferenceStack.textContent=formatBytes(inference.stack_high_water_mark_bytes);"
    "healthTaskStack.textContent=formatBytes(snapshot.health_stack_high_water_mark_bytes);"
    "healthPsram.textContent=`${formatBytes(snapshot.memory.psram.free_bytes)} / "
    "${formatBytes(snapshot.memory.psram.minimum_free_bytes)}`;"
    "const reasons=decodeHealthReasons(Number(snapshot.reason_flags));"
    "healthReasons.hidden=reasons.length===0;healthReasons.textContent=reasons.join(' · ');"
    "setHealthPanelState(true,true,snapshot.state);}"
    "function appendHealthSample(snapshot){if(!snapshot.ready||"
    "snapshot.sequence===lastHealthSequence)return;"
    "lastHealthSequence=snapshot.sequence;healthHistory.push(snapshot);"
    "if(healthHistory.length>60)healthHistory.splice(0,healthHistory.length-60);"
    "renderHealthSnapshot(snapshot);renderHealthCharts();}"
    "function setHealthConnectionError(message){healthSubtitle.textContent=message;"
    "healthState.textContent='Unknown';healthState.className='health-state starting';}"
    "async function pollHealth(){if(healthRequestRunning)return;"
    "healthRequestRunning=true;try{const response=await fetch('/api/health',"
    "{cache:'no-store'});if(!response.ok)throw new Error(`health HTTP ${response.status}`);"
    "const snapshot=await response.json();if(!snapshot.enabled){stopHealthPolling();"
    "clearHealthHistory();setHealthPanelState(false,false,'off');return;}"
    "setHealthPanelState(true,Boolean(snapshot.ready),snapshot.state);"
    "if(snapshot.ready)appendHealthSample(snapshot);startHealthPolling();"
    "}catch(error){setHealthConnectionError('连接中断 / 状态未知');}"
    "finally{healthRequestRunning=false;}}"
    "async function discoverHealthState(){await pollHealth();}"
    "async function setHealthEnabled(enabled){if(healthTransitioning)return;"
    "healthTransitioning=true;healthToggle.disabled=true;"
    "try{const response=await fetch('/api/health/control',{method:'POST',"
    "headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled})});"
    "if(!response.ok)throw new Error(`control HTTP ${response.status}`);"
    "const state=await response.json();if(state.enabled){"
    "setHealthPanelState(true,Boolean(state.ready),state.state);"
    "if(state.ready)appendHealthSample(state);startHealthPolling();}else{"
    "stopHealthPolling();clearHealthHistory();setHealthPanelState(false,false,'off');}"
    "}catch(error){setHealthConnectionError('连接中断 / 状态未知');}"
    "finally{healthTransitioning=false;healthToggle.disabled=false;}}"
    "healthToggle.addEventListener('click',()=>{"
    "setHealthEnabled(healthToggle.getAttribute('aria-checked')!=='true');});"
    "document.addEventListener('visibilitychange',()=>{"
    "if(document.visibilityState==='visible')discoverHealthState();});"
    "livePreview.addEventListener('error',()=>{if(liveReconnectTimer===null){"
    "liveReconnectTimer=setTimeout(startStream,1000);}});"
    "startStream();pollInference();setInterval(pollInference,1000);"
    "discoverHealthState();"
    "</script></main></body></html>";

const char *http_capture_dashboard_html(void)
{
    return DASHBOARD_HTML;
}
